# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 671))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Demowidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.Demowidget.setEnabled(False)
        self.Demowidget.setObjectName("Demowidget")
        self.horizontalLayout.addWidget(self.Demowidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(
            QtCore.QRect(990, 0, 291, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Demolist = QtWidgets.QListWidget(self.centralwidget)
        self.Demolist.setObjectName("Demolist")
        self.verticalLayout.addWidget(self.Demolist)
        self.Text = QtWidgets.QLabel(self.centralwidget)
        self.Text.setObjectName("Text")
        self.verticalLayout.addWidget(self.Text)
        self.Next_Target_Motion = QtWidgets.QLabel(self.centralwidget)
        self.Next_Target_Motion.setObjectName("Next_Target_Motion")
        self.verticalLayout.addWidget(self.Next_Target_Motion)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(
            QtCore.QRect(989, 469, 291, 201))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Camera = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Camera.setObjectName("Camera")
        self.horizontalLayout_3.addWidget(self.Camera)

        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(
            0, self.GUIDemo_height - 100, self.window_width, int(self.window_height*0.05)))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.SlideLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.SlideLayout.setContentsMargins(0, 0, 0, 0)
        self.SlideLayout.setObjectName("SlideLayout")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, int(
            self.window_height*0.95 - 100), self.window_width, int(self.window_height*0.05)))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")

        self.timeSlider = QtWidgets.QSlider(self.centralwidget)
        self.timeSlider.setEnabled(True)
        self.timeSlider.setMaximum(99)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.SlideLayout.addWidget(self.timeSlider)

        self.buttonLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_5)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("SlideLayout")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setObjectName("pause_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setObjectName("next_button")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setObjectName("previous_button")
        self.buttonLayout.addWidget(self.start_button)
        self.buttonLayout.addWidget(self.pause_button)
        self.buttonLayout.addWidget(self.previous_button)
        self.buttonLayout.addWidget(self.next_button)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSelect_file = QtWidgets.QAction(MainWindow)
        self.actionSelect_file.setObjectName("actionSelect_file")
        self.menuExit.addAction(self.actionSelect_file)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Text.setText(_translate("MainWindow", ""))
        self.Next_Target_Motion.setText(_translate("MainWindow", ""))
        self.Camera.setText(_translate("MainWindow", ""))
        self.menuExit.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSelect_file.setText(_translate("MainWindow", "Select file"))

        self.start_button.setText(_translate("MainWindow", "Start"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
